### ISSUE TITLE
Stylish compatibility

### ISSUE THREAD

**Issue by nathancahill** [rreusser/the-old-github-font#7]
Want to add a note on how to use the CSS with [Stylish](https://userstyles.org/)? Some might prefer it over installing a whole new extension for a couple rules of CSS.

```
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("github.com") {
    // css here
}
```

**Comment by rreusser** [comment]
Will do! Didn't know about that. Thanks!

**Comment by TWiStErRob** [comment]
That escalated quickly. Just a few hours ago this extension didn't exist... and now, it's obsolete ;)
Came to issues to tell you exactly that Stylish exists. I can't believe you have 66 stars and 4 forks already!

Here's a Stylish snippet from Chrome's Mozilla format export:
```css
@-moz-document domain("github.com"), domain("gist.github.com") {
body,
.intgrs-page .main-content,
.blog-content,
.migration-wrapper,
.migrate-owners-wrapper,
.setup-wrapper,
.showcase-page-title,
.tooltipped::after
{
	font-family: Helvetica, arial, nimbussansl, liberationsans, freesans, clean, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important;
}

.markdown-body
{
	font-family: "Helvetica Neue", Helvetica, "Segoe UI", Arial, freesans, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important;
}

body
{
	font-size: 13px !important;
	line-height: 1.4 !important;
}
}
```
